from django.urls import path
from . import views, api_views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),

    path('farmer/products/', views.farmer_products, name='farmer_products'),
    path('farmer/products/add/', views.add_product, name='add_product'),
    path('farmer/products/edit/<int:pk>/', views.edit_product, name='edit_product'),
    path('farmer/products/delete/<int:pk>/', views.delete_product, name='delete_product'),
    path('farmer/orders/', views.farmer_orders, name='farmer_orders'),
    path('farmer/orders/update/<int:pk>/', views.update_order_status, name='update_order_status'),
    path('farmer/earnings/', views.farmer_earnings_view, name='farmer_earnings'),

    path('products/', views.product_list, name='product_list'),
    path('cart/add/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('cart/remove/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/coupon/apply/', views.apply_coupon, name='apply_coupon'),
    path('cart/coupon/remove/', views.remove_coupon, name='remove_coupon'),
    path('cart/checkout/', views.place_order, name='place_order'),
    path('orders/', views.my_orders, name='my_orders'),
    path('orders/review/<int:order_pk>/', views.add_review_view, name='add_review'),

    path('admin-dashboard/', views.admin_dashboard_view, name='admin_dashboard'),

    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile_view, name='edit_profile'),
    path('settings/', views.settings_view, name='settings'),
    path('support/', views.support_view, name='support'),
    path('about/', views.about_view, name='about'),

    path('api/profile/', api_views.api_profile, name='api_profile'),
    path('api/categories/', api_views.api_categories, name='api_categories'),
    path('api/products/', api_views.api_products, name='api_products'),
    path('api/products/<int:pk>/', api_views.api_product_detail, name='api_product_detail'),
    path('api/products/add/', api_views.api_add_product, name='api_add_product'),
    path('api/products/edit/<int:pk>/', api_views.api_edit_product, name='api_edit_product'),
    path('api/products/delete/<int:pk>/', api_views.api_delete_product, name='api_delete_product'),
    path('api/orders/', api_views.api_my_orders, name='api_my_orders'),
    path('api/orders/place/', api_views.api_place_order, name='api_place_order'),
    path('api/orders/update/<int:pk>/', api_views.api_update_order, name='api_update_order'),
    path('api/cart/', api_views.api_cart, name='api_cart'),
    path('api/cart/add/<int:pk>/', api_views.api_add_to_cart, name='api_add_to_cart'),
    path('api/cart/update/<int:pk>/', api_views.api_update_cart_item, name='api_update_cart_item'),
    path('api/cart/remove/<int:pk>/', api_views.api_remove_from_cart, name='api_remove_from_cart'),
    path('api/coupon/apply/', api_views.api_apply_coupon, name='api_apply_coupon'),
    path('api/products/<int:product_pk>/review/', api_views.api_add_review, name='api_add_review'),
    path('api/notifications/', api_views.api_notifications, name='api_notifications'),
    path('api/notifications/read/', api_views.api_mark_notifications_read, name='api_notifications_read'),
    path('api/subscriptions/', api_views.api_subscriptions, name='api_subscriptions'),
    path('api/subscriptions/cancel/<int:pk>/', api_views.api_cancel_subscription, name='api_cancel_subscription'),
    path('api/farmer/earnings/', api_views.api_farmer_earnings, name='api_farmer_earnings'),
    path('api/delivery/available/', api_views.api_available_deliveries, name='api_available_deliveries'),
    path('api/delivery/accept/<int:pk>/', api_views.api_accept_delivery, name='api_accept_delivery'),
    path('api/delivery/location/', api_views.api_update_location, name='api_update_location'),
    path('api/razorpay/create-order/', api_views.api_razorpay_create_order, name='api_razorpay_create'),
    path('api/razorpay/verify/', api_views.api_razorpay_verify, name='api_razorpay_verify'),
    path('api/admin/analytics/', api_views.api_admin_analytics, name='api_admin_analytics'),
]